name: trs-conversion
version: 0.6.0.0
git: "https://git.uibk.ac.at/informatik/cl/ari/task-a/trs-conversion"
license:            GPL-3.0-only
license-file:       LICENSE
author:
  - "Fabian Mitterwallner"
  - "Jamie Fox"
maintainer: "Fabian Mitterwallner <fabian.mittewallner@uibk.ac.at>"
copyright:
  - "2023 Jamie Fox"
  - "2023-2024 Fabian Mitterwallner"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - stack.yaml

# Metadata used when publishing your package
synopsis: TRS format converter
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Package to convert between the COPS and ARI rewriting problem formats.

  See the README.md or at
  <https://git.uibk.ac.at/informatik/cl/ari/task-a/trs-conversion/-/blob/main/README.md>
  for more information.

dependencies:
  - base >= 4.7 && < 5
  - prettyprinter >= 1.7.1 && < 1.8
  - megaparsec >=9.3.0 && < 9.7
  - text >= 2.0.1 && < 2.2
  - containers >= 0.6.0.1 && < 0.8
  - xml-conduit >= 1.9.1.1 && < 1.10
  - xml-hamlet >= 0.5.0.2 && < 0.6
  - tpdb >= 2.7.2
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  trs-conversion:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -rtsopts
    dependencies:
      - trs-conversion

  format-type:
    main: Main.hs
    source-dirs: format-type
    ghc-options:
      - -rtsopts
    dependencies:
      - trs-conversion
  ari-syntax-checker:
    main: Main.hs
    source-dirs: ari-syntax-checker
    ghc-options:
      - -rtsopts
    dependencies:
      - trs-conversion

tests:
  trs-conversion-hspec:
    main: Spec.hs
    source-dirs: test-hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - trs-conversion
      - hspec >= 2.10.0.1 && < 2.12
      - hspec-discover
      - hedgehog
      - hspec-hedgehog
      - text
    build-tools: hspec-discover:hspec-discover == 2.*
